add_newline = true

format = """
$username$hostname$directory$git_branch$git_status$python$nodejs$ruby$cmd_duration$line_break$character"""

[username]
show_always = true
format = "[$user](bold cyan)"

[hostname]
ssh_only = false
format = "[@$hostname](cyan) "

[directory]
truncation_length = 3
truncate_to_repo = false
format = "[$path](bold blue) "

[git_branch]
format = "on [$branch](bold green) "

[git_status]
format = '([$staged$modified$untracked$deleted$ahead_behind](208)) '
staged = '✚ '
modified = '● '
untracked = '+ '
deleted = '✖ '
ahead = '⇡${count} '
behind = '⇣${count} '
diverged = '⇡${ahead_count} ⇣${behind_count} '

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

[cmd_duration]
min_time = 3_000
format = "took [$duration](bold 208) "

[nodejs]
format = "[$symbol$version](green) "
detect_files = ["package.json"]
detect_folders = ["node_modules"]
symbol = " "

[python]
format = "[$symbol$version](208) "
detect_files = ["requirements.txt", "pyproject.toml", "setup.py", "Pipfile"]
detect_folders = [".venv", "venv"]
symbol = " "

[ruby]
format = "[$symbol$version](red) "
detect_files = ["Gemfile", ".ruby-version"]
symbol = " "

[docker_context]
format = "[$symbol$context](blue) "
symbol = " "
only_with_files = true
